_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 53
                - 55
                - 105
            "2":
                - 5
                - 53
                - 55
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
lr_all:
    value: 0.005
n_epochs:
    value: 20
n_factors:
    value: 50
reg_all:
    value: 0.02
