version: '3.8'

services:
  book-recommender:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATA_PATH=/app/data/ukr_books_dataset.csv
      - EMBEDDINGS_PATH=/app/models/embeddings.npy
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3