apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      incrementalQuerying: false
      exemplarTraceIdDestinations: []
      manageAlerts: true
      alertmanagerUid: ""
    
  - name: SigNoz
    type: prometheus  
    access: proxy
    url: http://signoz:4318
    isDefault: false
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'Medium'
      disableMetricsLookup: true
      incrementalQuerying: false