wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.19.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745593825
    t:
      1:
      - 53
      - 55
      - 105
      2:
      - 53
      - 55
      - 105
      3:
      - 14
      - 23
      - 37
      4: 3.12.3
      5: 0.19.10
      8:
      - 5
      13: linux-x86_64
lr_all:
  desc: null
  value: 0.005
n_factors:
  desc: null
  value: 100
reg_all:
  desc: null
  value: 0.05
