# PIPELINE DEFINITION
# Name: hw7-train-pipeline
# Inputs:
#    data_path: str [Default: 'data/ukr_books_dataset.csv']
#    model_dir: str [Default: 'models/']
components:
  comp-load-data-component:
    executorLabel: exec-load-data-component
    inputDefinitions:
      parameters:
        data_path:
          parameterType: STRING
    outputDefinitions:
      parameters:
        Output:
          parameterType: STRING
  comp-train-component:
    executorLabel: exec-train-component
    inputDefinitions:
      parameters:
        data_path:
          parameterType: STRING
        model_dir:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-load-data-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - load_data_component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.13.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef load_data_component(data_path: str) -> str:\n    return data_path\n\
          \n"
        image: python:3.9
    exec-train-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.13.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_component(data_path: str, model_dir: str):\n    from src\
          \ import train\n    train.train_model(data_path, model_dir)\n\n"
        image: python:3.9
pipelineInfo:
  name: hw7-train-pipeline
root:
  dag:
    tasks:
      load-data-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-load-data-component
        inputs:
          parameters:
            data_path:
              componentInputParameter: data_path
        taskInfo:
          name: load-data-component
      train-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-component
        dependentTasks:
        - load-data-component
        inputs:
          parameters:
            data_path:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: load-data-component
            model_dir:
              componentInputParameter: model_dir
        taskInfo:
          name: train-component
  inputDefinitions:
    parameters:
      data_path:
        defaultValue: data/ukr_books_dataset.csv
        isOptional: true
        parameterType: STRING
      model_dir:
        defaultValue: models/
        isOptional: true
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
