apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-recommender
  namespace: ml-hw12
  labels:
    app: book-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-recommender
  template:
    metadata:
      labels:
        app: book-recommender
    spec:
      containers:
      - name: book-recommender
        image: book-recommender:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics
        envFrom:
        - configMapRef:
            name: book-recommender-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3