apiVersion: v1
kind: Service
metadata:
  name: book-recommender-service
  namespace: ml-hw12
  labels:
    app: book-recommender
spec:
  type: ClusterIP
  selector:
    app: book-recommender
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8001
    targetPort: 8000
    protocol: TCP