name: CI

on:
  push:
    branches: [ student ]
  pull_request:
    branches: [ student ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Клон репозиторію
      - uses: actions/checkout@v4

      # 2) Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3) Кеш pip (прискорює повторні ранти)
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) Встановлення залежностей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hw6/requirements.txt

      # 5) Запуск pytest
      - name: Run tests
        env:
          PYTHONPATH: hw6/src
          WANDB_MODE: offline       # блокуємо зовн. логування
        run: |
          pytest -q
